# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        host_patterns:
            - ^api\.
    documentation:
      info:
        version: v1
        title: Hefesto Express Prisma APIs
        description: Hefesto Express Prisma APIs
        contact:
          name: Henrique Figueiredo de Souza
        license:
          name: Apache 2.0
          url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
      servers:
        - url: 'http://localhost:3000/api/v1'
          description: Local server
